version: '3.6'

services:
  redis:
    container_name: ddev-${DDEV_SITENAME}-redis
    image: redis:4
    ports:
      - 6390
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
      com.ddev.app-url: $DDEV_URL
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=6390
    volumes: []
    networks: [default, ddev_default]
  web:
    links:
      - redis:redis